import { AutoProcessor, AutoModelForVision2Seq, TextStreamer, InterruptableStoppingCriteria, load_image } from 'https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/+esm';
const MODEL='HuggingFaceTB/SmolVLM-256M-Instruct';
let processorPromise=null, modelPromise=null, fp16=false; const stopping=new InterruptableStoppingCriteria();
async function check(){try{if(!navigator.gpu) throw new Error('WebGPU tidak tersedia di browser ini.'); const adapter=await navigator.gpu.requestAdapter(); if(!adapter) throw new Error('WebGPU tidak menemukan GPU adapter.'); fp16=adapter.features.has('shader-f16'); postMessage({status:'ready'});}catch(e){postMessage({status:'error',data:e.toString()})}}
function progress(x){postMessage(x)}
async function get(){processorPromise ??= AutoProcessor.from_pretrained(MODEL,{progress_callback:progress}); modelPromise ??= AutoModelForVision2Seq.from_pretrained(MODEL,{dtype:{embed_tokens:fp16?'fp16':'fp32',vision_encoder:'q4',decoder_model_merged:'q4'},device:'webgpu',progress_callback:progress}); return Promise.all([processorPromise,modelPromise])}
async function load(){postMessage({status:'loading',data:'Memuat SmolVLM…'});await get();postMessage({status:'ready'})}
async function generate(messages){try{const [processor,model]=await get();const images=await Promise.all(messages.map(x=>x.content).flat(Infinity).filter(x=>x.image!==undefined).map(x=>load_image(x.image)));const text=processor.apply_chat_template(messages,{add_generation_prompt:true});const inputs=await processor(text,images,{do_image_splitting:false});let streamed='';const streamer=new TextStreamer(processor.tokenizer,{skip_prompt:true,skip_special_tokens:true,callback_function:t=>{streamed+=t;postMessage({status:'update',output:t})}});const ids=await model.generate({...inputs,do_sample:false,repetition_penalty:1.05,max_new_tokens:650,streamer,stopping_criteria:stopping});const decoded=processor.batch_decode(ids.slice(null,[inputs.input_ids.dims.at(-1),null]),{skip_special_tokens:true});postMessage({status:'complete',output:decoded});}catch(e){postMessage({status:'error',data:e?.stack||e?.toString()||String(e)})}}
self.onmessage=e=>{const {type,data}=e.data;if(type==='check')check();else if(type==='load')load();else if(type==='generate'){stopping.reset();generate(data)}else if(type==='interrupt')stopping.interrupt()};
